### PR TITLE
Alt-Tab and Meta-Ctrl-Esc button combo for non-Holo ISO Linux users

### PR DESCRIPTION
**Pull request by ghost573**
Adds two button combinations for anyone on Linux but not Holo ISO like myself.

Personally find these absolutely necessary in the instance a game misbehaves or require changing a setting if a game is already open.

Feel free to change the names if these aren't satisfactory or you intend to use them for something else, I'm not great at naming things.

### CODE REVIEW

**Comment by pastaq** [comment]
You'll need to add the events to the event map or the strings from the config file wont match to anything. Can you change the first one to `EVENT_ALT_TAB` for verbosity purposes as well?

https://github.com/ShadowBlip/HandyGCCS/blob/8582463f86d5ad77e4b5beb1fbef8679e213a472/handycon.py#L53

**Comment by ghost573** [comment]
Sure thing.

**Comment by pastaq** [comment]
Alt tab works great. Is that other shortcut a custom one? It doesn't appear to b ea default shortcut for gnome or kde that I can find, and it does nothing on Manjaro or ChimeraOS as far as I can tell.

**Comment by pastaq** [comment]
Nevermind, I found the reference in KDE. Thats fine. Everything seems to test good. Thanks for your contribution.

**Pull request merged**
