### PR TITLE
Change the ff capture to forward effects.

### PR DESCRIPTION
**Pull request by alphonsez1**
Change the implementation so that rumble can reuse effects that are uploaded. To use Rumble, you'll need to disable Steam Input in the game. It turns out https://github.com/ValveSoftware/steam-for-linux/issues/8590 is blocking the Rumble being taking effect when Steam Input is enabled.

I tested in 2 games: Ori and the blind forest, and Tunic. This PR is working well in both of the games. 

This is a re-submit of https://github.com/ShadowBlip/HandyGCCS/pull/30 which I closed since it didn't work as expected in Tunic. The bug was fixed.

### CODE REVIEW

**Comment by alphonsez1** [comment]
From the games I tried so far, it's still true that the games always re-upload the effect right before using them. Maybe it's proton that is doing it. So this change doesn't really make a difference in the games.
Maybe the only difference so far is that it makes `fftest` work as expected.

**Comment by pastaq** [comment]
Same as the other PR on my availability. I'm curious to know if this improves the FF effects themselves. I like the error catching. Thanks for your contributions, and I'm sorry I don't have more time to dedicate right now.

**Comment by alphonsez1** [comment]
I tried it and it didn't really feel different. I further tested, it seems the `strong_magnitude` and `weak_magnitude` doesn't make a difference when it's above a threashold (something above 300). So it seems the driver doesn't really support the magnitude. I recently reinstalled Windows on my Ayaneo Air. The windows driver also behaves the same.

**Comment by danyi** [comment]
I have an AIR pro

I think I can help with the test

**Comment by pastaq** [comment]
> I tried it and it didn't really feel different. I further tested, it seems the `strong_magnitude` and `weak_magnitude` doesn't make a difference when it's above a threashold (something above 300). So it seems the driver doesn't really support the magnitude. I recently reinstalled Windows on my Ayaneo Air. The windows driver also behaves the same.

Even so, this is a better way of handling this in any case. I'll test it this week on my 3 devices and let you know how it works out.

**Pull request merged**
