### PR TITLE
Fix the game controller fails after sleep

### PR DESCRIPTION
**Pull request by danyi**
Fix 6.0linux kernel or higher
The game controller fails after sleep

### CODE REVIEW

**Comment by pastaq** [comment]
Can you add a comment in the code what this is doing/why?

**Comment by danyi** [comment]
Recognize the controller again after wake up
And get the controller again

**Comment by pastaq** [comment]
So if i'm understanding properly, sometimes when coming out of sleep, the original controller device has been reinitialized by udev and is in /dev/input, and this just puts it back into /dev/input/.hidden?

**Comment by pastaq** [comment]
Bump?

**Comment by pastaq** [comment]
This was automatically closed when I merged the target branch into main. If this is still necessary please resubmit it with a more clear explanation of what you're trying to accomplish.

**Pull request closed without merging**
